# Data with Pandas

In [35]:
import pandas as pd

In [36]:
from pathlib import Path

# Pfad zur Datei (relativ zum Notebook)
csv_path = Path("../data/eistage.csv")

df = pd.read_csv(
    csv_path,
    sep=";",                # Semikolon als Trennzeichen
    skiprows=[0, 1],             # erste Zeile (Beschreibungstext) überspringen
    low_memory=False,      # Warnung bei gemischten Datentypen unterdrücken
    encoding="utf-8",       # ggf. "latin-1" falls Umlaute kaputt sind
    usecols=[3, 5, 6],  # nur die Spalten "Datum", "Eistage" und "Eistage_5J" laden],
    nrows=70,
    names=["year", "heat_days", "ice_days"],
    parse_dates=["year"],
)

print(df.shape)
print(df.dtypes)
df.head()

(70, 3)
year         datetime64[ns]
heat_days             int64
ice_days              int64
dtype: object

        year  heat_days  ice_days
0 1955-01-01          1        25
1 1956-01-01          3        46
2 1957-01-01         10        20
3 1958-01-01          9        11
4 1959-01-01          5        17

## Überblick

In [37]:
df.head(2) #Ersten 2 Zeilen anzeigen

        year  heat_days  ice_days
0 1955-01-01          1        25
1 1956-01-01          3        46

In [38]:
df.tail(2) #Letzten 2 Zeilen anzeigen

         year  heat_days  ice_days
68 2023-01-01         32         2
69 2024-01-01         45         2

In [39]:
df.info() #Informationen über die Spalten und Datentypen anzeigen

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   year       70 non-null     datetime64[ns]
 1   heat_days  70 non-null     int64
 2   ice_days   70 non-null     int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.8 KB

In [40]:
df.describe() #Statistische Kennzahlen für numerische Spalten anzeigen

                                year  heat_days   ice_days
count                             70  70.000000  70.000000
mean   1989-07-02 05:49:42.857142912  15.371429  20.414286
min              1955-01-01 00:00:00   0.000000   2.000000
25%              1972-04-01 12:00:00   6.500000  12.250000
50%              1989-07-02 12:00:00  13.000000  19.500000
75%              2006-10-01 18:00:00  21.000000  25.000000
max              2024-01-01 00:00:00  45.000000  63.000000
std                              NaN  11.007470  12.062029